### ISSUE TITLE
Hello dv-123

### ISSUE THREAD

**Issue by SumitSingh109** [dv-123/Lung_cancer#3]
Good Job! Really appreciate the code. Just wondering, how did you create the data folder, with all the image slices?

Thanks in Advance

**Comment by dv-123** [comment]
I have done it in the lung_cancer.ipynb, but this method is not effective in training as during the slicing we also need to keep in check the labels for the individual slices, this problem is not tackled yet. Once this problem is solved the model will be trained efficiently and only then the training data will be accurate.
